#!/bin/bash

#SBATCH --job-name=fuel_mult1
#SBATCH --output=unit_cell.o

#SBATCH --error=unit_cell.error

#SBATCH --partition=savio2

#SBATCH --time=72:00:00

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=1

#SBATCH--cpus-per-task=24

# QoS: savio_normal

#SBATCH --qos=savio_normal

# Account:

#SBATCH -A fc_neutronics

#SBATCH --mail-user=yves.robert@berkeley.edu
#SBATCH --mail-type=all

# run command
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
mpirun -np 1 --map-by ppr:1:node:pe=24 /global/home/users/yvesrobert/Softwares/serpent2.1.31_gcc/sss2 -omp 24 fhr

